name: unfolding
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipywidgets
  - ipympl
  - tqdm
  - pytest
  - pip
  - dask
  - zarr
  - pip:
    - pymeshlab
    - fast_simplification