# Conda environment installing necessary packages 
name: unfolding
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - jupyterlab
  - ipywidgets
  - tqdm
  - pip
  - pip:
    - pymeshlab